### ISSUE TITLE
Images aren't loading

### ISSUE THREAD

**Issue by t-schroeder** [moodleuulm/moodle-theme_boost_campus_child#1]
After recently upgrading the boost_campus theme I noticed that many icons and pictures were broken. Then I saw this warning in my log:

> file_get_contents(/path/to/moodle/theme/boost_campus/scss/pre.scss): failed to open stream: No such file or directory in /path/to/moodle/theme/boost_campus_child/lib.php on line 71

When I create an empty pre.scss in boost_campus the error is gone. All icons and pictures load normally again.

**Comment by Kathrin84** [comment]
Hi do-you-even-curl,
thank you for this hint and the provided solution. 
We deleted the pre.scss file in boost_campus because we removed all rules there and thought that this file the is not necessary anymore.
But as you encountered this problem, I added it to boost_campus again:
https://github.com/moodleuulm/moodle-theme_boost_campus/commit/5e5b59258e97c6699015686193abb0e60002154f
This will be part of the release v3.4-r4 of boost_campus.
As I assume that this issue will be fixed with the provided patch, I close it.
Best, Kathrin
